### ISSUE TITLE
[Bug] Path Patterns not working?

### ISSUE THREAD

**Issue by Regala** [dariusztytko/progress-burp#3]
Hey,

I'm having issues using the path patterns feature. e.g. I was expecting that if I add a pattern like your example `/article/\d+?/comments` I would see that being added and shown in the Path Patterns tab. It seems it's not being added nor it is being processed to group the requests.

Using the latest version available in the BApp store.

**Comment by dariusztytko** [comment]
Hi,

Probably selected item lost focus in the meantime (because of adding a new item). In general, items selection must to be kept until the end of any context menu action. This can be problematic for applications with lots of JavaScript "background" requests. You can turn off capturing for a while to work around the problem.

Thanks you for your feedback.

**Comment by Regala** [comment]
Interesting. After you add a valid path pattern, would the affected items immediately "disappear" from the table or it is only applied from that point on? I *think* added successfully by turning off the capture in the extension and the proxy itself, and the item I selected gets removed. I still don't see any pattern being shown in the Path Patterns tab though 🙁

Follow up question - can you "remove" path patterns?

**Comment by dariusztytko** [comment]
I didn't notice any problems. Is there any information in the "Extender -> Extensions -> Progress Tracker -> Errors" tab?

When path pattern is added all matched items (except selected one) are removed. "Path patterns" tab should contain added regexp and there  should be possibility to remove it (context-menu action).

**Comment by Regala** [comment]
No errors or output I'm afraid. It seems they are being applied, but the "Path patterns" tab is never populated.. I'm using v1.1 from the BApp store and Burp v2020.4 btw.

**Comment by dariusztytko** [comment]
It's interesting. What OS do you use? Has it ever worked for you?

**Comment by Regala** [comment]
Never worked I'm afraid. Mac OSX Catalina. Do you have any debug version I can spin up?

**Comment by dariusztytko** [comment]
Sounds like a clue (it was tested only on Windows and Linux). I'll prepare repository with developer version and send you invitation to collaborate.

**Comment by Regala** [comment]
Sounds good my dude 🙏

**Comment by dariusztytko** [comment]
There's actually no reason to not public it: https://github.com/dariusztytko/progress-tracker-dev. There are a lot of files. It was my "hexagonal architecture" experiments ground :)

**Comment by Regala** [comment]
Alright! Cloned, compiled it and did the usual tests and no luck. Let me know if you need anything from my side.

**Comment by Regala** [comment]
I believe this was a problem with a specific Burp version; it started working so the extension is fine 👌
